# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: List

items:

# --------------------------=== pod 0 ===--------------------------

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pbft-0
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: pbft-0
    template:
      metadata:
        labels:
          name: pbft-0
      spec:
        containers:
          - name: sawtooth-intkey-tp-python
            image: hyperledger/sawtooth-intkey-tp-python:nightly
            command:
              - bash
            args:
              - -c
              - "intkey-tp-python -vv -C tcp://$HOSTNAME:4004"

          - name: sawtooth-pbft-engine
            image: blockchaintp/sawtooth-pbft-engine:BTP2.1.0
            command:
              - bash
            args:
              - -c
              - "pbft-engine -vv --connect tcp://$HOSTNAME:5050"

          - name: sawtooth-rest-api
            image: blockchaintp/sawtooth-rest-api:BTP2.1.0
            ports:
              - name: api
                containerPort: 8008
            command:
              - bash
            args:
              - -c
              - "sawtooth-rest-api -vv -C tcp://$HOSTNAME:4004 -B 0.0.0.0:8008"
            readinessProbe:
              httpGet:
                path: /status
                port: 8008
              initialDelaySeconds: 15
              periodSeconds: 10

          - name: sawtooth-settings-tp
            image: blockchaintp/sawtooth-settings-tp:BTP2.1.0
            command:
              - bash
            args:
              - -c
              - "settings-tp -vv -C tcp://$HOSTNAME:4004"

          - name: sawtooth-shell
            image: blockchaintp/sawtooth-shell:BTP2.1.0
            command:
              - bash
            args:
              - -c
              - "sawtooth keygen && tail -f /dev/null"

          - name: sawtooth-seth-tp
            image: blockchaintp/sawtooth-seth-tp:BTP2.1.0rc13-0.2.3p1
            command:
              - bash
            args:
              - -c
              - "seth-tp -vv -C tcp://HOSTNAME:4004"

          - name: sawtooth-seth-rpc
            image: blockchaintp/sawtooth-seth-rpc:BTP2.1.0rc13-0.2.3p1
            command:
              - bash
            args:
              - -c
              - "seth-rpc -vv --connect tcp://validator:4004 --bind 0.0.0.0:3030"

          - name: sawtooth-seth-cli
            image: blockchaintp/sawtooth-seth-cli:BTP2.1.0rc13-0.2.3p1
            command:
              - bash
            args:
              - -c
              - |
                 tail -f /dev/null

          - name: sawtooth-smallbank-tp-rust
            image: hyperledger/sawtooth-smallbank-tp-rust:nightly
            command:
              - bash
            args:
              - -c
              - "smallbank-tp-rust -vv -C tcp://$HOSTNAME:4004"

          - name: sawtooth-validator
            image: blockchaintp/sawtooth-validator:BTP2.1.0
            ports:
              - name: tp
                containerPort: 4004
              - name: consensus
                containerPort: 5050
              - name: validators
                containerPort: 8800
            envFrom:
              - configMapRef:
                  name: keys-config
            command:
              - bash
            args:
              - -c
              - |
                  if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
                    echo $pbft0priv > /etc/sawtooth/keys/validator.priv
                    echo $pbft0pub > /etc/sawtooth/keys/validator.pub
                  fi &&
                  if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
                    sawtooth keygen my_key
                  fi &&
                  if [ ! -e config-genesis.batch ]; then
                    sawset genesis -k /root/.sawtooth/keys/my_key.priv -o config-genesis.batch
                  fi &&
                  sleep 10 &&
                  echo sawtooth.consensus.pbft.members=["\"$pbft0pub\",\"$pbft1pub\",\"$pbft2pub\",\"$pbft3pub\",\"$pbft4pub\""] &&
                  if [ ! -e config.batch ]; then
                    sawset proposal create \
                      -k /root/.sawtooth/keys/my_key.priv \
                      sawtooth.consensus.algorithm.name=pbft \
                      sawtooth.consensus.algorithm.version=1.0\
                      sawtooth.consensus.pbft.members=["\"$pbft0pub\",\"$pbft1pub\",\"$pbft2pub\",\"$pbft3pub\",\"$pbft4pub\""] \
                      sawtooth.publisher.max_batches_per_block=1200 \
                      -o config.batch
                  fi && \
                  if [ ! -e /var/lib/sawtooth/genesis.batch ]; then
                    sawadm genesis config-genesis.batch config.batch
                  fi &&
                  sawtooth-validator -vv \
                    --endpoint tcp://$SAWTOOTH_0_SERVICE_HOST:8800 \
                    --bind component:tcp://eth0:4004 \
                    --bind consensus:tcp://eth0:5050 \
                    --bind network:tcp://eth0:8800 \
                    --scheduler parallel \
                    --peering static \
                    --maximum-peer-connectivity 10000

          - name: sawtooth-xo-tp-python
            image: hyperledger/sawtooth-xo-tp-python:nightly
            command:
              - bash
            args:
              - -c
              - "xo-tp-python -vv -C tcp://$HOSTNAME:4004"

- apiVersion: v1
  kind: Service
  metadata:
    name: sawtooth-0
  spec:
    type: ClusterIP
    selector:
      name: pbft-0
    ports:
      - name: "4004"
        protocol: TCP
        port: 4004
        targetPort: 4004
      - name: "5050"
        protocol: TCP
        port: 5050
        targetPort: 5050
      - name: "8008"
        protocol: TCP
        port: 8008
        targetPort: 8008
      - name: "8080"
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: "8800"
        protocol: TCP
        port: 8800
        targetPort: 8800
